const body=document.body,themeBtn=document.getElementById('themeBtn'),hamburger=document.getElementById('hamburger'),navMenu=document.getElementById('navMenu');
if(localStorage.getItem('portfolio-theme')==='dark'){body.classList.add('dark');if(themeBtn)themeBtn.textContent='☀️';}
if(themeBtn)themeBtn.addEventListener('click',()=>{body.classList.toggle('dark');const dark=body.classList.contains('dark');localStorage.setItem('portfolio-theme',dark?'dark':'light');themeBtn.textContent=dark?'☀️':'🌙';});
if(hamburger)hamburger.addEventListener('click',()=>navMenu.classList.toggle('open'));
document.querySelectorAll('.nav-menu a').forEach(a=>a.addEventListener('click',()=>navMenu.classList.remove('open')));
const observer=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');e.target.querySelectorAll('.bar i').forEach(b=>b.style.width=b.dataset.width)}}),{threshold:.12});
document.querySelectorAll('.reveal').forEach(e=>observer.observe(e));
const progress=document.getElementById('progress');window.addEventListener('scroll',()=>{const h=document.documentElement.scrollHeight-innerHeight;progress.style.width=(scrollY/h*100)+'%';});
const year=document.getElementById('year');if(year)year.textContent=new Date().getFullYear();
const form=document.getElementById('contactForm');if(form)form.addEventListener('submit',e=>{e.preventDefault();let ok=true;const name=document.getElementById('name'),email=document.getElementById('email'),message=document.getElementById('message');const ne=document.getElementById('nameError'),ee=document.getElementById('emailError'),me=document.getElementById('messageError'),status=document.getElementById('formStatus');ne.textContent=ee.textContent=me.textContent=status.textContent='';if(name.value.trim().length<2){ne.textContent='Enter your name.';ok=false}if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email.value.trim())){ee.textContent='Enter a valid email.';ok=false}if(message.value.trim().length<10){me.textContent='Message must contain at least 10 characters.';ok=false}if(ok){status.textContent='Message validated successfully.';form.reset()}});
const modal=document.getElementById('articleModal');if(modal){const title=document.getElementById('modalTitle'),text=document.getElementById('modalText');document.querySelectorAll('.read-more').forEach(btn=>btn.addEventListener('click',()=>{title.textContent=btn.dataset.title;text.textContent=btn.dataset.text;modal.classList.add('show')}));document.getElementById('closeModal').addEventListener('click',()=>modal.classList.remove('show'));modal.addEventListener('click',e=>{if(e.target===modal)modal.classList.remove('show')});}
